# Generated by Django 3.0.4 on 2020-05-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_username'),
        ('education_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
