# Generated by Django 3.0.4 on 2020-05-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question_statement',
        ),
    ]
