# Generated by Django 3.0.4 on 2020-05-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200504_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_statement',
            new_name='statement',
        ),
    ]
