# Generated by Django 3.0.4 on 2020-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200424_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilenumber',
            old_name='phone_number',
            new_name='mobile_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
