# Generated by Django 3.0.4 on 2020-04-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200426_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='mobilenumber',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email_id',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(db_column='gender_id', on_delete=django.db.models.deletion.CASCADE, to='user.Gender'),
        ),
    ]
