# Generated by Django 3.0.4 on 2020-05-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200517_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='mobilenumber',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
            preserve_default=False,
        ),
    ]
